%% criar_modelo_xplane.m - Gera o modelo Simulink xplane_autopilot.slx
% Este script cria programaticamente o modelo Simulink que integra
% o autopiloto PID com o X-Plane via XPlaneConnect.
%
% Pre-requisito: rodar inicializar_xplane antes.
%
% Uso:
%   >> inicializar_xplane
%   >> criar_modelo_xplane
%   >> open('Xplane/xplane_autopilot.slx')

%% ========== Configuracao ==========
modelName = 'xplane_autopilot';
slxPath = fullfile(fileparts(mfilename('fullpath')), [modelName '.slx']);

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist(slxPath, 'file')
    delete(slxPath);
end

%% ========== Criar modelo ==========
new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'Ts_xplane', ...
    'StopTime', 'inf', ...
    'EnablePacing', 'on', ...
    'PacingRate', '1');

set_param(modelName, 'StopFcn', 'close_xplane');
set_param(modelName, 'InitFcn', ...
    ['if ~exist(''Ts_xplane'',''var''), ' ...
     'error(''Rode inicializar_xplane antes de simular!''); end']);

%% ========== Helpers ==========
m = modelName;  % abreviacao

% Funcao para posicao: pos(x, y, w, h)
pos = @(x, y, w, h) [x, y, x+w, y+h];

%% ========================================================================
%%  SECAO 1: LEITURA DE SENSORES (topo)
%% ========================================================================
% Layout: Trigger -> Read_XPlane -> Demux -> Goto tags (verticais)

add_block('simulink/Sources/Constant', [m '/Trigger'], ...
    'Value', '0', ...
    'Position', pos(30, 60, 40, 25));

add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
    [m '/Read_XPlane'], ...
    'MATLABFcn', 'read_xplane', ...
    'OutputDimensions', '10', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(110, 50, 130, 45));

add_line(m, 'Trigger/1', 'Read_XPlane/1');

% Demux 10 saidas
add_block('simulink/Signal Routing/Demux', [m '/Demux'], ...
    'Outputs', '10', ...
    'Position', pos(290, 20, 8, 120));

add_line(m, 'Read_XPlane/1', 'Demux/1');

% --- Goto tags para cada sinal ---
% Nomes: VT, theta, q, h, phi, p, psi, r, xN, xE
tags = {'VT','theta','q','h','phi','p','psi','r','xN','xE'};
for i = 1:10
    gotoName = ['Goto_' tags{i}];
    yg = 15 + (i-1)*12;
    add_block('simulink/Signal Routing/Goto', [m '/' gotoName], ...
        'GotoTag', tags{i}, ...
        'TagVisibility', 'local', ...
        'Position', pos(330, yg, 55, 14));
    add_line(m, ['Demux/' num2str(i)], [gotoName '/1']);
end

%% ========================================================================
%%  SECAO 2: LONGITUDINAL - ALTITUDE + THETA + VELOCIDADE
%% ========================================================================
% Tres faixas horizontais com boa separacao vertical.

% --- Coordenadas base ---
yAlt   = 200;   % faixa altitude
yTheta = 300;   % faixa theta (pitch)
yVel   = 420;   % faixa velocidade

xFrom  = 60;    % From blocks
xRef   = 60;    % Constant refs
xSum1  = 220;   % Sum (erro)
xPID   = 320;   % PID
xSAS   = 500;   % SAS sum
xSat   = 590;   % Saturacao

% ===================== ALTITUDE =====================
% h_ref → (+/-) Sum_alt → PID_alt → theta_ref (output)

add_block('simulink/Sources/Constant', [m '/h_ref'], ...
    'Value', 'h_ref', ...
    'Position', pos(xRef, yAlt, 50, 25));

add_block('simulink/Signal Routing/From', [m '/From_h'], ...
    'GotoTag', 'h', ...
    'Position', pos(xFrom, yAlt+40, 45, 14));

add_block('simulink/Math Operations/Sum', [m '/Sum_alt'], ...
    'Inputs', '+-', ...
    'Position', pos(xSum1, yAlt+10, 30, 30));

add_line(m, 'h_ref/1', 'Sum_alt/1');
add_line(m, 'From_h/1', 'Sum_alt/2');

add_block('simulink/Discrete/Discrete PID Controller', [m '/PID_alt'], ...
    'Controller', 'PID', ...
    'P', 'C_alt.Kp', 'I', 'C_alt.Ki', 'D', 'C_alt.Kd', 'N', 'C_alt.N', ...
    'SampleTime', 'Ts_xplane', ...
    'UpperSaturationLimit', '0.26', ...
    'LowerSaturationLimit', '-0.17', ...
    'AntiWindupMode', 'Clamping', ...
    'Position', pos(xPID, yAlt, 90, 45));

add_line(m, 'Sum_alt/1', 'PID_alt/1');

% ===================== THETA (PITCH) =====================
% PID_alt output → (+/-) Sum_theta ← theta → PID_theta → (+/-) Sum_elev ← Kq*q → Sat_elev

add_block('simulink/Signal Routing/From', [m '/From_theta'], ...
    'GotoTag', 'theta', ...
    'Position', pos(xFrom, yTheta+40, 55, 14));

add_block('simulink/Math Operations/Sum', [m '/Sum_theta'], ...
    'Inputs', '+-', ...
    'Position', pos(xSum1, yTheta+10, 30, 30));

add_line(m, 'PID_alt/1', 'Sum_theta/1');
add_line(m, 'From_theta/1', 'Sum_theta/2');

add_block('simulink/Discrete/Discrete PID Controller', [m '/PID_theta'], ...
    'Controller', 'PID', ...
    'P', 'C_theta.Kp', 'I', 'C_theta.Ki', 'D', 'C_theta.Kd', 'N', 'C_theta.N', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xPID, yTheta, 90, 45));

add_line(m, 'Sum_theta/1', 'PID_theta/1');

% SAS: Kq * q
add_block('simulink/Signal Routing/From', [m '/From_q'], ...
    'GotoTag', 'q', ...
    'Position', pos(xPID, yTheta+65, 40, 14));

add_block('simulink/Math Operations/Gain', [m '/Kq_gain'], ...
    'Gain', 'Kq', ...
    'Position', pos(xPID+60, yTheta+60, 40, 25));

add_line(m, 'From_q/1', 'Kq_gain/1');

% Sum: PID_theta - Kq*q
add_block('simulink/Math Operations/Sum', [m '/Sum_elev'], ...
    'Inputs', '+-', ...
    'Position', pos(xSAS, yTheta+10, 30, 30));

add_line(m, 'PID_theta/1', 'Sum_elev/1');
add_line(m, 'Kq_gain/1', 'Sum_elev/2');

% Saturacao elevator
add_block('simulink/Discontinuities/Saturation', [m '/Sat_elev'], ...
    'UpperLimit', '0.4363', 'LowerLimit', '-0.4363', ...
    'Position', pos(xSat, yTheta+10, 45, 30));

add_line(m, 'Sum_elev/1', 'Sat_elev/1');

% ===================== VELOCIDADE =====================
% VT_ref → (+/-) Sum_vel ← VT → PID_vel → (++) Sum_thr ← Ue(1) → Sat_thr

add_block('simulink/Sources/Constant', [m '/VT_ref'], ...
    'Value', 'VT_ref', ...
    'Position', pos(xRef, yVel, 50, 25));

add_block('simulink/Signal Routing/From', [m '/From_VT'], ...
    'GotoTag', 'VT', ...
    'Position', pos(xFrom, yVel+40, 45, 14));

add_block('simulink/Math Operations/Sum', [m '/Sum_vel'], ...
    'Inputs', '+-', ...
    'Position', pos(xSum1, yVel+10, 30, 30));

add_line(m, 'VT_ref/1', 'Sum_vel/1');
add_line(m, 'From_VT/1', 'Sum_vel/2');

add_block('simulink/Discrete/Discrete PID Controller', [m '/PID_vel'], ...
    'Controller', 'PID', ...
    'P', 'C_vel.Kp', 'I', 'C_vel.Ki', 'D', 'C_vel.Kd', 'N', 'C_vel.N', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xPID, yVel, 90, 45));

add_line(m, 'Sum_vel/1', 'PID_vel/1');

% Trim throttle: + Ue(1)
add_block('simulink/Sources/Constant', [m '/Thr_trim'], ...
    'Value', 'Ue(1)', ...
    'Position', pos(xPID+60, yVel+60, 50, 25));

add_block('simulink/Math Operations/Sum', [m '/Sum_thr'], ...
    'Inputs', '++', ...
    'Position', pos(xSAS, yVel+10, 30, 30));

add_line(m, 'PID_vel/1', 'Sum_thr/1');
add_line(m, 'Thr_trim/1', 'Sum_thr/2');

% Saturacao throttle
add_block('simulink/Discontinuities/Saturation', [m '/Sat_thr'], ...
    'UpperLimit', '1', 'LowerLimit', '0', ...
    'Position', pos(xSat, yVel+10, 45, 30));

add_line(m, 'Sum_thr/1', 'Sat_thr/1');

%% ========================================================================
%%  SECAO 3: LATERAL - HEADING + ROLL + YAW
%% ========================================================================

yHdg = 570;   % faixa heading -> phi_ref
yPhi = 670;   % faixa roll
yYaw = 790;   % faixa yaw damper

% ===================== HEADING → PHI_REF =====================
% psi_ref, psi → Heading_Error → 0.3 gain → phi_ref

add_block('simulink/Sources/Constant', [m '/psi_ref'], ...
    'Value', 'psi_ref', ...
    'Position', pos(xRef, yHdg, 55, 25));

add_block('simulink/Signal Routing/From', [m '/From_psi'], ...
    'GotoTag', 'psi', ...
    'Position', pos(xFrom, yHdg+40, 45, 14));

add_block('simulink/Signal Routing/Mux', [m '/Mux_psi'], ...
    'Inputs', '2', ...
    'Position', pos(xSum1-20, yHdg+5, 8, 40));

add_line(m, 'psi_ref/1', 'Mux_psi/1');
add_line(m, 'From_psi/1', 'Mux_psi/2');

add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
    [m '/Heading_Error'], ...
    'MATLABFcn', '@(u) atan2(sin(u(1)-u(2)), cos(u(1)-u(2)))', ...
    'OutputDimensions', '1', ...
    'SampleTime', '-1', ...
    'Position', pos(xSum1+20, yHdg+5, 110, 35));

add_line(m, 'Mux_psi/1', 'Heading_Error/1');

add_block('simulink/Math Operations/Gain', [m '/Heading_gain'], ...
    'Gain', '0.3', ...
    'Position', pos(xPID+40, yHdg+10, 50, 25));

add_line(m, 'Heading_Error/1', 'Heading_gain/1');

% ===================== ROLL =====================
% phi_ref → (+/-) Sum_phi ← phi → PID_phi → (+/-) Sum_ail ← Kp_sas*p → Sat_ail

add_block('simulink/Signal Routing/From', [m '/From_phi'], ...
    'GotoTag', 'phi', ...
    'Position', pos(xFrom, yPhi+40, 45, 14));

add_block('simulink/Math Operations/Sum', [m '/Sum_phi'], ...
    'Inputs', '+-', ...
    'Position', pos(xSum1, yPhi+10, 30, 30));

add_line(m, 'Heading_gain/1', 'Sum_phi/1');
add_line(m, 'From_phi/1', 'Sum_phi/2');

add_block('simulink/Discrete/Discrete PID Controller', [m '/PID_phi'], ...
    'Controller', 'PID', ...
    'P', 'C_phi.Kp', 'I', 'C_phi.Ki', 'D', 'C_phi.Kd', 'N', 'C_phi.N', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xPID, yPhi, 90, 45));

add_line(m, 'Sum_phi/1', 'PID_phi/1');

% SAS: Kp_sas * p
add_block('simulink/Signal Routing/From', [m '/From_p'], ...
    'GotoTag', 'p', ...
    'Position', pos(xPID, yPhi+65, 40, 14));

add_block('simulink/Math Operations/Gain', [m '/Kp_sas_gain'], ...
    'Gain', 'Kp_sas', ...
    'Position', pos(xPID+60, yPhi+60, 55, 25));

add_line(m, 'From_p/1', 'Kp_sas_gain/1');

add_block('simulink/Math Operations/Sum', [m '/Sum_ail'], ...
    'Inputs', '+-', ...
    'Position', pos(xSAS, yPhi+10, 30, 30));

add_line(m, 'PID_phi/1', 'Sum_ail/1');
add_line(m, 'Kp_sas_gain/1', 'Sum_ail/2');

add_block('simulink/Discontinuities/Saturation', [m '/Sat_ail'], ...
    'UpperLimit', '0.4363', 'LowerLimit', '-0.4363', ...
    'Position', pos(xSat, yPhi+10, 45, 30));

add_line(m, 'Sum_ail/1', 'Sat_ail/1');

% ===================== YAW DAMPER =====================
% r → Washout → Kr → Sat_rud

add_block('simulink/Signal Routing/From', [m '/From_r'], ...
    'GotoTag', 'r', ...
    'Position', pos(xFrom, yYaw+10, 40, 14));

add_block('simulink/Discrete/Discrete Transfer Fcn', [m '/Washout_r'], ...
    'Numerator', '[1 -1]', ...
    'Denominator', '[1 -exp(-Ts_xplane)]', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xSum1, yYaw, 100, 40));

add_line(m, 'From_r/1', 'Washout_r/1');

add_block('simulink/Math Operations/Gain', [m '/Kr_gain'], ...
    'Gain', 'Kr', ...
    'Position', pos(xSAS, yYaw+5, 40, 25));

add_line(m, 'Washout_r/1', 'Kr_gain/1');

add_block('simulink/Discontinuities/Saturation', [m '/Sat_rud'], ...
    'UpperLimit', '0.4363', 'LowerLimit', '-0.4363', ...
    'Position', pos(xSat, yYaw+3, 45, 30));

add_line(m, 'Kr_gain/1', 'Sat_rud/1');

%% ========================================================================
%%  SECAO 4: SAIDA - MUX + ENVIO
%% ========================================================================

xMux = 720;
xSend = 800;
yMux = yTheta;  % alinhado com theta ate yaw

% Mux: [delta_e, delta_a, delta_r, delta_T]
add_block('simulink/Signal Routing/Mux', [m '/Mux_Ctrl'], ...
    'Inputs', '4', ...
    'Position', pos(xMux, yMux, 8, 530));

add_line(m, 'Sat_elev/1', 'Mux_Ctrl/1');  % elevator
add_line(m, 'Sat_thr/1', 'Mux_Ctrl/2');   % throttle
add_line(m, 'Sat_ail/1', 'Mux_Ctrl/3');   % aileron
add_line(m, 'Sat_rud/1', 'Mux_Ctrl/4');   % rudder

% Envio ao X-Plane
add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
    [m '/Send_XPlane'], ...
    'MATLABFcn', 'send_xplane', ...
    'OutputDimensions', '1', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xSend, yVel+5, 130, 45));

add_line(m, 'Mux_Ctrl/1', 'Send_XPlane/1');

%% ========================================================================
%%  SECAO 5: MONITORAMENTO (scopes e logging, coluna da direita)
%% ========================================================================

xScope = 1020;

% --- Scope Attitude (theta, phi, psi) ---
add_block('simulink/Signal Routing/From', [m '/From_theta_s'], ...
    'GotoTag', 'theta', 'Position', pos(xScope-90, yAlt, 55, 14));
add_block('simulink/Signal Routing/From', [m '/From_phi_s'], ...
    'GotoTag', 'phi', 'Position', pos(xScope-90, yAlt+20, 45, 14));
add_block('simulink/Signal Routing/From', [m '/From_psi_s'], ...
    'GotoTag', 'psi', 'Position', pos(xScope-90, yAlt+40, 45, 14));

add_block('simulink/Signal Routing/Mux', [m '/Mux_Att'], ...
    'Inputs', '3', ...
    'Position', pos(xScope-20, yAlt, 8, 55));

add_line(m, 'From_theta_s/1', 'Mux_Att/1');
add_line(m, 'From_phi_s/1', 'Mux_Att/2');
add_line(m, 'From_psi_s/1', 'Mux_Att/3');

add_block('simulink/Sinks/Scope', [m '/Scope_Attitude'], ...
    'NumInputPorts', '1', ...
    'Position', pos(xScope+10, yAlt+5, 50, 45));

add_line(m, 'Mux_Att/1', 'Scope_Attitude/1');

% --- Scope Alt + Vel ---
add_block('simulink/Signal Routing/From', [m '/From_h_s'], ...
    'GotoTag', 'h', 'Position', pos(xScope-90, yTheta, 40, 14));
add_block('simulink/Signal Routing/From', [m '/From_VT_s'], ...
    'GotoTag', 'VT', 'Position', pos(xScope-90, yTheta+25, 45, 14));

add_block('simulink/Signal Routing/Mux', [m '/Mux_AltVel'], ...
    'Inputs', '2', ...
    'Position', pos(xScope-20, yTheta, 8, 40));

add_line(m, 'From_h_s/1', 'Mux_AltVel/1');
add_line(m, 'From_VT_s/1', 'Mux_AltVel/2');

add_block('simulink/Sinks/Scope', [m '/Scope_AltVel'], ...
    'NumInputPorts', '1', ...
    'Position', pos(xScope+10, yTheta+5, 50, 35));

add_line(m, 'Mux_AltVel/1', 'Scope_AltVel/1');

% --- Scope Controls ---
add_block('simulink/Sinks/Scope', [m '/Scope_Controls'], ...
    'NumInputPorts', '1', ...
    'Position', pos(xScope+10, yVel+5, 50, 35));

add_line(m, 'Mux_Ctrl/1', 'Scope_Controls/1');

% --- To Workspace: sensores ---
add_block('simulink/Sinks/To Workspace', [m '/Log_Sensors'], ...
    'VariableName', 'xplane_sensors', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xScope+10, yHdg, 85, 30));

add_line(m, 'Read_XPlane/1', 'Log_Sensors/1');

% --- To Workspace: controles ---
add_block('simulink/Sinks/To Workspace', [m '/Log_Controls'], ...
    'VariableName', 'xplane_controls', ...
    'SampleTime', 'Ts_xplane', ...
    'Position', pos(xScope+10, yHdg+50, 85, 30));

add_line(m, 'Mux_Ctrl/1', 'Log_Controls/1');

%% ========== ANOTACOES ==========
add_block('built-in/Note', [m '/Note_Title'], ...
    'Position', [30, 10, 430, 10], ...
    'Text', 'X-Plane Autopilot - Piper J-3 Cub 1/6');

add_block('built-in/Note', [m '/Note_Long'], ...
    'Position', [60, yAlt-15, 500, yAlt-15], ...
    'Text', '=== LONGITUDINAL (Altitude + Pitch + Velocidade) ===');

add_block('built-in/Note', [m '/Note_Lat'], ...
    'Position', [60, yHdg-15, 500, yHdg-15], ...
    'Text', '=== LATERAL (Heading + Roll + Yaw Damper) ===');

add_block('built-in/Note', [m '/Note_Mon'], ...
    'Position', [xScope-20, yAlt-15, xScope+200, yAlt-15], ...
    'Text', '=== MONITORAMENTO ===');

%% ========== SALVAR ==========
save_system(modelName, slxPath);
disp(' ');
disp(['=== Modelo criado: ' slxPath ' ===']);
disp('  Para usar:');
disp('    1) Abrir X-Plane com Piper J-3 Cub');
disp('    2) >> inicializar_xplane');
disp('    3) >> open(''Xplane/xplane_autopilot.slx'')');
disp('    4) Simular (Ctrl+T)');
disp(' ');
disp('  Para parar: Ctrl+C ou botao Stop no Simulink');
